### PR TITLE
feat(CD): add semantic release

### PR DESCRIPTION
**Pull request by AntoineDao**
The commits in this PR will enable semantic release to a package called `uwg` (which does not exist yet). There are a few more steps to carry out in order to make this possible however:

1. Tag the ladybug-tools UWG repository with the latest version 
```console
git tag v5.0.0
git push origin v5.0.0
```
2. Add Travis environment variables to the build [like this](https://docs.travis-ci.com/user/environment-variables/#Defining-Variables-in-Repository-Settings)
  * GH_TOKEN: a github token generated by the owner of the ladybug-tools repo (this will allow travis to commit and tag new releases to the repo). **Make it secret**
  *  PYPI_USERNAME: the PyPi username who will be in charge of releasing 
  * PYPI_PASSWORD: the PyPi user's password. **Make it secret**

3. Merge this PR

4. ???

5. Bath in the joys of effortless automation.

### CODE REVIEW

**Comment by mostaphaRoudsari** [comment]
@AntoineDao, @saeranv I added Travis environment variables for all the repositories including uwg! I leave the rest to you guys.

Also Ladybug Tools now has a user account on PyPI: https://pypi.org/user/ladybug-tools/

**Comment by saeranv** [comment]
@AntoineDao sorry for the late response, just got back from a vacation. I can tag, merge, and hopefully resolve the conflicts here. 

Are we releasing this as version 1.0.0?

`git tag v1.0.0`
`git push origin v1.0.0`

Thanks for pushing this ahead @AntoineDao!

**Comment by AntoineDao** [comment]
Reckon we should be safe to merge with master. Worse comes to worse we have tests to tell us if it has all gone wrong! My understanding was that uwg was currently at v5.0.0 so I have it set up to start at that version (semantic-release will freak out if the latest tagged version is different from the version in the repo so we need to fix that).

I am not fussed which version we start at so if you want to make it v1.0.0 then make sure to change the following line:
https://github.com/ladybug-tools/uwg/blob/99cb27c02dcdd70a56551d68d2c467ce27e3a8ee/uwg/__init__.py#L3

**Comment by chriswmackey** [comment]
This is great!

As for the version of the UWG, [I had announced the Python version as version 5.0](https://discourse.ladybug.tools/t/dragonfly-0-0-3-and-urban-weather-generator-5-0-released/3250), mostly out of respect for the history of the engine and for the many others who have worked on it before us.  Furthermore, now that the python version exists, I don't think that @hansukyang is editing the matlab version so we should not be in conflict with the any continued versions of the Matlab UWG.

I would say go ahead and keep the version as 5.0.

**Comment by saeranv** [comment]
@chriswmackey @AntoineDao sounds good I'll do it tonight!

**Comment by AntoineDao** [comment]
Just noticed semantic-release command was set to version and not publish. We had this issue with @mostaphaRoudsari with ladybug. Also changed the bot user to `ladybug-bot`.

**Comment by hansukyang** [comment]
Great work! FYI, I haven't worked on UWG since leaving MIT but I believe
Jiachen Mao (Les' student) continued to use the Matlab version although I
don't if he released any changes as new revision. In any case, I think the
Python version can continue to evolve as a separate entity.

**Comment by saeranv** [comment]
@AntoineDao 

Okay, I think I've merged all the changes. I made a mistake by merging before doing the git tagging (does order matter?) so I had to revert the change, did the git tag and then added the changes back. So it's messy but I believe it is done. 

Let me know if I made a mistake somewhere, and I'll fix it. I'll withhold any celebration till then.

**Comment by AntoineDao** [comment]
Hmm not 100% sure that work. Tagging commit 9f5cf0b33b64ab48352237a853fb17725c0059e5 as v5.0.0 and then reapplication of the current settings without using (semantic-release git commit style)[https://blog.greenkeeper.io/introduction-to-semantic-release-33f73b117c8] has resulted in no changes being detected by semantic-release. I would recommend one of two options:

1. Reset head to 9f5cf0b33b64ab48352237a853fb17725c0059e5 by running the following locally:
```console
git checkout master
git reset head --hard 9f5cf0b33b64ab48352237a853fb17725c0059e5
git push --force
```
2. Add some minor change and use semantic-release git commit style `type-of-commit(affected topic): comments` and see what happens. This should work from now on regardless but we must make sure we use the appropriate git commit syntax.

I would personally prefer the first option as it will make the git history look a bit cleaner however understand if you want to commit to some strict `don't touch master branch policy`. If the tag disappears you can just add it again and rerun travis without committing new content and it should all be fine.

**Comment by AntoineDao** [comment]
Scratch that it totally [worked](https://travis-ci.org/ladybug-tools/uwg/jobs/451291607)!

**Comment by saeranv** [comment]
Hooray! Thanks for pushing this through!

**Comment by AntoineDao** [comment]
Next step is adding some semi-automated [documentation](https://docs.readthedocs.io/en/latest/intro/getting-started-with-sphinx.html) right?

**Pull request merged**
