### PR TITLE
feat(*): add python 3.6 support

### PR DESCRIPTION
**Pull request by AntoineDao**
In preparation for the [Python-pocalypse](https://pythonclock.org/) we should add python 3 support. This PR should solve [this issue](https://github.com/ladybug-tools/uwg/issues/75). Here is an initial proposal on how to do so. 

The main strategies involve the following:
1. `xrange` is replaced by variable name `range` and provided with backwards compatibility like so:
```python
try:
    range = xrange # Will work if running Python 2
except NameError:
    pass                  # If Python 3 can just use normal range
```
2. Printing like an adult 
```python
print("like an adult") # GOOD
print "like a child"     # BAD
```
3. Relative imports are used 
```python
import .local_file # GOOD
import local_file  # BAD
```
4. Importing division behaviour from Python 3 
```python
from __future__ import division
```
5. There was also a peculiar case of csv import errors with decrypting info in python 3 which I resolved in lines 25-28:
https://github.com/ladybug-tools/uwg/blob/03a328f44a05a4b2cd10e1bee18f2e4f76cae5f9/uwg/utilities.py#L22-L35

### CODE REVIEW

**Comment by chriswmackey** [comment]
This is great @AntoineDao .  Thank you for doing this and @saeranv should look it over.

**Comment by AntoineDao** [comment]
From my understanding using `from __future__ import print_function` is used to enforce a certain behaviour when printing multiple objects in one statetment.
### ptyhon 2
```python
>>> print(1, 2)
(1, 2)
>>> from __future__ import print_function
>>> print(1, 2)
1 2
```
### ptyhon 3
```python
>>> print(1, 2)
1 2
```
I did not notice any such cases of print in UWG (to be fair I didn't look in depth) so didn't see the need to add it. Happy to have it as an addition if you reckon it's necessary 👍

**Comment by saeranv** [comment]
Yes, if you could add it that would be great. I think it is more consistent with expected behaviour we have in Python 2, and just better practice overall. 

Other than that, we're good.

**Comment by AntoineDao** [comment]
@saeranv as per requested I have imported `print_function` from `__future__`.

**Comment by saeranv** [comment]
Thanks @AntoineDao looks good! I merged it, and made some minor edits on top of it with this PR: https://github.com/ladybug-tools/uwg/commit/4beddbc093ce572e2da5cbb3ea5ab2b04f3b2f8c , I moved the print_function module to the same line as the division, which I think is a cleaner way to import from packages. I also noticed, unrelated to all of this, that there was an extra UWG.py floating around that I had to delete. 

Thanks again, 

-S

**Pull request merged**
